### ISSUE TITLE
Convert Tensor object to array object

### ISSUE THREAD

**Issue by kgeyer** [jamesyili/rTensor#12]
I'm new to using rTensor, and so far I think it's great. I like that you guys kept it similar to Kolda's Tensor Toolbox (which I previously used).

My question for you is, how can I convert a Tensor object (after applying as.tensor to an array object) to either an array or matrix object? It seems like there's no method for this task (pls tell me otherwise). 

Thanks in advance for your help; I hope to hear from you soon. Keep up the good work!

**Comment by kgeyer** [comment]
Hey, you can extract the array by the following:

First make tensor object A, then extract the attribute 'data' 

`A = rand_tensor(modes = c(3, 4, 5), drop = FALSE);
B = attr(A, 'data');
class(B);
`

**Comment by jkh1** [comment]
For the record, rTensor objects are S4 R objects so one can also access the array as A@data or slot(A, "data"). A@data is the recommended method for accessing slots of S4 objects.

**Comment by kgeyer** [comment]
Thanks a lot!

Kelly
